

#ifndef CONF_BOARD_H
#define CONF_BOARD_H

#include <asf.h>

#include <conf_ArduinoM0Pro_board.h>


// Interface Wi-Fi
#define XE910_PIN_RESET   PIN_PA07
#define XE910_BAUDRATE    115200
#define XE910_DATABIT     USART_CHARACTER_SIZE_8BIT
#define XE910_STOPBIT     USART_STOPBITS_1
#define XE910_PARITY      USART_PARITY_NONE

#define COM3_PIN_RESET      PIN_PA07
#define COM3_BAUDRATE       115200
#define COM3_DATABIT        USART_CHARACTER_SIZE_8BIT
#define COM3_STOPBIT        USART_STOPBITS_1
#define COM3_PARITY         USART_PARITY_NONE

// Interface Serial
#define SERIAL_BAUDRATE     115200
#define SERIAL_DATABIT      USART_CHARACTER_SIZE_8BIT
#define SERIAL_STOP_BITS    USART_STOPBITS_1
#define SERIAL_PARITY       USART_PARITY_NONE

// Interface Serial2
#define SERIAL2_BAUDRATE    XE910_BAUDRATE
#define SERIAL2_DATABIT     XE910_DATABIT
#define SERIAL2_STOP_BITS   XE910_STOPBIT
#define SERIAL2_PARITY      XE910_PARITY

// Interface Serial3
#define SERIAL3_BAUDRATE    COM3_BAUDRATE
#define SERIAL3_DATABIT     COM3_DATABIT
#define SERIAL3_STOP_BITS   COM3_STOPBIT
#define SERIAL3_PARITY      COM3_PARITY

#endif // CONF_BOARD_H
